#!/bin/bash

FILE=${1}
INDEX=${FILE}.bai
CHROMSIZES=${FILE}.chromsizes
BEDGRAPH=${FILE}.bedgraph
BIGWIG=${FILE}.bw


# if file does not exist, create index
if [ ! -f $INDEX ]; then
	echo "Indexing $FILE"
	samtools index $FILE
fi

# chromsizes file does not exist, create it
if [ ! -f $CHROMSIZES ]; then
	echo "Creating $CHROMSIZES"
	samtools idxstats $FILE | awk '{print $1"\t"$2}' > $CHROMSIZES
fi

# convert to bedgraph
echo "Creating $BEDGRAPH"
samtools depth -q 30 -Q 10 $FILE |
    awk -v FS="\t" -v OFS="\t" '($3 > 0){
        if (NR>1 && ($1!=prev_seq || $3!=prev_cov || $2>prev_pos+1)) {
            print prev_seq,start,end,prev_cov
            start = $2-1
        } else if(NR==1) {
            start = $2-1
        }
        end = $2
        prev_seq = $1
        prev_pos = $2
        prev_cov = $3
    } END {print prev_seq,start,end,prev_cov}' |
    sort -k1,1 -k2,2n > $BEDGRAPH


# create bigwig
echo "Creating $BIGWIG"
bedGraphToBigWig $BEDGRAPH $CHROMSIZES $BIGWIG

# cleanup intermedioary files
echo "Cleaning up"
#rm $BEDGRAPH $CHROMSIZES
